### ISSUE TITLE
Game fails to create save file.

### ISSUE THREAD

**Issue by MrSoup678** [Derpford/laser-justice#1]
Trying to save through any possible way (QuickSave, Save Game, save command) falis, with log stating:

```
Attempt to save pointer to unhandled type NativeStruct<CVar>
```

After running gzdoom under debugger I can now pinpoint bad lines.

https://github.com/Derpford/laser-justice/blob/71c77bbdca526db11eb389c3479ff5f514c8a108/zscript/damped.zs#L9

**Comment by Derpford** [comment]
Should be fixed now, the CVars have been marked as transient

**Comment by Derpford** [comment]
This should be a trivial fix; I forgot that CVars have to be marked
`transient`.
